using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ERPToolAPI.Models
{
    public class ERPItem
    {
        public string item { get; set; }
        public string description { get; set; }

        //[Column(TypeName = "decimal?(20, 8)")]
        public decimal? qty_allocjob { get; set; }

        public string u_m { get; set; }

        public short? lead_time { get; set; }
        public decimal? lot_size { get; set; }
        public decimal? qty_used_ytd { get; set; }
        public decimal? qty_mfg_ytd { get; set; }
        public string abc_code { get; set; }
        public string drawing_nbr { get; set; }
        public string product_code { get; set; }
        public string p_m_t_code { get; set; }
        public string cost_method { get; set; }
        public decimal? lst_lot_size { get; set; }
        public decimal? unit_cost { get; set; }
        public decimal? lst_u_cost { get; set; }
        public decimal? avg_u_cost { get; set; }
        public string job { get; set; }
        public short? suffix { get; set; }
        public byte? stocked { get; set; }
        public string matl_type { get; set; }
       
        public string family_code { get; set; }
        public byte? low_level { get; set; }
        public DateTime? last_inv { get; set; }
        public short? days_supply { get; set; }
        public decimal? order_min { get; set; }
        public decimal? order_mult { get; set; }
        public string plan_code { get; set; }
        public byte? mps_flag { get; set; }
        public byte? accept_req { get; set; }
        public DateTime? change_date { get; set; }
        public string revision { get; set; }
        public byte? phantom_flag { get; set; }
        public byte? plan_flag { get; set; }
        public short? paper_time { get; set; }
        public short? dock_time { get; set; }
        public decimal? asm_setup { get; set; }
        public decimal? asm_run { get; set; }
        public decimal? asm_matl { get; set; }
        public decimal? asm_tool { get; set; }
        public decimal? asm_fixture { get; set; }
        public decimal? asm_other { get; set; }
        public decimal? asm_fixed { get; set; }
        public decimal? asm_var { get; set; }
        public decimal? asm_outside { get; set; }
        public decimal? comp_setup { get; set; }
        public decimal? comp_run { get; set; }
        public decimal? comp_matl { get; set; }
        public decimal? comp_tool { get; set; }
        public decimal? comp_fixture { get; set; }
        public decimal? comp_other { get; set; }
        public decimal? comp_fixed { get; set; }
        public decimal? comp_var { get; set; }
        public decimal? comp_outside { get; set; }
        public decimal? sub_matl { get; set; }
        public decimal? shrink_fact { get; set; }
        public string alt_item { get; set; }
        public decimal? unit_weight { get; set; }
        public string weight_units { get; set; }
        public string charfld4 { get; set; }
        public decimal? cur_u_cost { get; set; }
        public string feat_type { get; set; }
        public decimal? var_lead { get; set; }
        public string feat_str { get; set; }
        public short? next_config { get; set; }
        public string feat_templ { get; set; }
        public byte? backflush { get; set; }
        public string charfld1 { get; set; }
        public string charfld2 { get; set; }
        public string charfld3 { get; set; }
        public decimal? decifld1 { get; set; }
        public decimal? decifld2 { get; set; }
        public decimal? decifld3 { get; set; }
        public byte? logifld { get; set; }
        public DateTime? datefld { get; set; }
        public byte? track_ecn { get; set; }
        public decimal? u_ws_price { get; set; }
        public string comm_code { get; set; }
        public string origin { get; set; }
        public decimal? unit_mat_cost { get; set; }
        public decimal? unit_duty_cost { get; set; }
        public decimal? unit_freight_cost { get; set; }
        public decimal? unit_brokerage_cost { get; set; }
        public decimal? cur_mat_cost { get; set; }
        public decimal? cur_duty_cost { get; set; }
        public decimal? cur_freight_cost { get; set; }
        public decimal? cur_brokerage_cost { get; set; }
        public string tax_code1 { get; set; }
        public string tax_code2 { get; set; }
        public string bflush_loc { get; set; }
        public byte? reservable { get; set; }
        public short? shelf_life { get; set; }
        public string lot_prefix { get; set; }
        public string serial_prefix { get; set; }
        public byte? serial_length { get; set; }
        public string issue_by { get; set; }
        public byte? serial_tracked { get; set; }
        public byte? lot_tracked { get; set; }
        public string cost_type { get; set; }
        public decimal? matl_cost { get; set; }
        public decimal? lbr_cost { get; set; }
        public decimal? fovhd_cost { get; set; }
        public decimal? vovhd_cost { get; set; }
        public decimal? out_cost { get; set; }
        public decimal? cur_matl_cost { get; set; }
        public decimal? cur_lbr_cost { get; set; }
        public decimal? cur_fovhd_cost { get; set; }
        public decimal? cur_vovhd_cost { get; set; }
        public decimal? cur_out_cost { get; set; }
        public decimal? avg_matl_cost { get; set; }
        public decimal? avg_lbr_cost { get; set; }
        public decimal? avg_fovhd_cost { get; set; }
        public decimal? avg_vovhd_cost { get; set; }
        public decimal? avg_out_cost { get; set; }
        public string prod_type { get; set; }
        public decimal? rate_per_day { get; set; }
        public short? mps_plan_fence { get; set; }
        public byte? pass_req { get; set; }
        public byte? lot_gen_exp { get; set; }
        public string supply_site { get; set; }
        public string prod_mix { get; set; }
        public string stat { get; set; }
        public string status_chg_user_code { get; set; }
        public DateTime? chg_date { get; set; }
        public string reason_code { get; set; }
        public string supply_whse { get; set; }
        public short? due_period { get; set; }
        public decimal? order_max { get; set; }
        public byte? mrp_part { get; set; }
        public byte? infinite_part { get; set; }
        public byte? NoteExistsFlag { get; set; }
        public DateTime? RecordDate { get; set; }
        public System.Guid RowPointer { get; set; }
        public decimal? supply_tolerance_hrs { get; set; }
        public short? exp_lead_time { get; set; }
        public decimal? var_exp_lead { get; set; }
        public string buyer { get; set; }
        public byte? order_configurable { get; set; }
        public byte? job_configurable { get; set; }
        public string cfg_model { get; set; }
        public string co_post_config { get; set; }
        public string job_post_config { get; set; }
        public string auto_job { get; set; }
        public string auto_post { get; set; }
        public string setupgroup { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public DateTime? CreateDate { get; set; }
        public byte? InWorkflow { get; set; }
        public byte? mfg_supply_switching_active { get; set; }
        public short? time_fence_rule { get; set; }
        public System.Double? time_fence_value { get; set; }
        public DateTime? earliest_planned_po_receipt { get; set; }
        public byte? use_reorder_point { get; set; }
        public decimal? reorder_point { get; set; }
        public decimal? fixed_order_qty { get; set; }
        public decimal? unit_insurance_cost { get; set; }
        public decimal? unit_loc_frt_cost { get; set; }
        public decimal? cur_insurance_cost { get; set; }
        public decimal? cur_loc_frt_cost { get; set; }
        public byte? tax_free_matl { get; set; }
        public short? tax_free_days { get; set; }
        public decimal? safety_stock_percent { get; set; }
        public string tariff_classification { get; set; }
        public DateTime? lowdate { get; set; }
        public string rcpt_rqmt { get; set; }
        public byte? active_for_data_integration { get; set; }
        public decimal? rcvd_over_po_qty_tolerance { get; set; }
        public decimal? rcvd_under_po_qty_tolerance { get; set; }
        public byte? include_in_net_change_planning { get; set; }
        public byte? kit { get; set; }
        public byte? print_kit_components { get; set; }
        public byte? include_in_net_change_generation { get; set; }
        public short? safety_stock_rule { get; set; }
        public byte? show_in_drop_down_list { get; set; }
        public byte? controlled_by_external_ics { get; set; }
        public decimal? inventory_ucl_tolerance { get; set; }
        public decimal? inventory_lcl_tolerance { get; set; }
        public string separation_attribute { get; set; }
        public System.Double? batch_release_attribute1 { get; set; }
        public System.Double? batch_release_attribute2 { get; set; }
        public System.Double? batch_release_attribute3 { get; set; }
        public string Uf_Emt_Std { get; set; }
        public string Uf_OperLoading { get; set; }
        public string Uf_Store_Cond { get; set; }
        public decimal? Uf_Thickness { get; set; }
        public string picture { get; set; }
        public byte? active_for_customer_portal { get; set; }
        public byte? featured { get; set; }
        public byte? top_seller { get; set; }
        public string overview { get; set; }
        public byte? Uf_Npi { get; set; }
        public string item_Type { get; set; }
        public string Material { get; set; }
        public decimal? lenght { get; set; }
        public decimal? width { get; set; }
        public DateTime? leadTime { get; set; }
        public decimal? density { get; set; }
        [NotMapped]
        public decimal? volume { get; set; }

    }
}
